// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TC_ZIP
{
    public string ZIP { get; set; }

    public byte? TodoufukenCD { get; set; }

    public string Todoufuken { get; set; }

    public short? ShikuCD { get; set; }

    public string Shiku { get; set; }

    public short? CyousonCD { get; set; }

    public string Cyouson { get; set; }
}