// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TC_データテーブル一覧
{
    public byte? No { get; set; }

    public byte? Class { get; set; }

    public string テーブル名 { get; set; }
}