// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TC_見積情報_QuoteInformation
{
    public string UserCD { get; set; }

    public int? 見積番号_QuotationNumber { get; set; }
}