// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TC_部署データ_TC_DepartmentData
{
    public string 部署CD_DepartmentCode { get; set; }

    public string 部署名_DepartmentName { get; set; }

    public int? 表示順_DisplayOrder { get; set; }
}