// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TI_工種データ_ConstructionTypeData
{
    public int? 見積番号_QuotationNumber { get; set; }

    public string 作成者CD_CreatorCode { get; set; }

    public int? 工種番号_WorkTypeNumber { get; set; }

    public int? 表示順_DisplaySequence { get; set; }

    public string 表示工種番号_DiplayWorkTypeNumber { get; set; }

    public byte? 工種FLG_Work_ConstructionTypeFlag { get; set; }

    public byte? 工種Child_ConstructionTypeChild { get; set; }

    public int? 工種CD_ConstructionTypeCode { get; set; }

    public string 工種名_ConstructionTypeName { get; set; }

    public float? 雑材消耗率_MiscellaneousMaterialConsumptionRate { get; set; }

    public bool? _雑材消耗FLG_MiscellaneousMaterialConsumptionFlag { get; set; }

    public bool? CL付属FLG_CLAccessoryFlag { get; set; }

    public bool? CL支持FLG_CLSupportFlag { get; set; }

    public bool? RW付属FLG_RWAccessoryFlag { get; set; }

    public bool? RW支持FLG_RWSupportFlag { get; set; }

    public bool? C補足材FLG_CAdditionalMaterialFlag { get; set; }

    public bool? 照明FLG_LightingFlag { get; set; }

    public bool? 盤FLG_PanelFlag { get; set; }

    public byte? 戸数_NumberOfUnits { get; set; }

    public decimal? 提出金額_AmountSubmitted { get; set; }

    public decimal? 社内金額_InHouseAmount { get; set; }

    public decimal? 機材費A_EquipmentCostA { get; set; }

    public decimal? 機材費B_EquipmentCostB { get; set; }

    public decimal? 雑材消耗品費A_MiscellaneousMaterialsExpenseA { get; set; }

    public decimal? 雑材消耗品費B_MiscellaneousMaterialsExpenseB { get; set; }

    public decimal? 労務費A_LaborCostA { get; set; }

    public decimal? 労務費B_LaborCostB { get; set; }

    public decimal? 付帯工事A_AssociatedConstructionA { get; set; }

    public decimal? 付帯工事B_AssociatedConstructionB { get; set; }

    public decimal? 共通費A_SharedExpensesA { get; set; }

    public decimal? 共通費B_SharedExpensesB { get; set; }

    public decimal? 現場雑費A_OnSiteMiscellaneousCostsA { get; set; }

    public decimal? 現場雑費B_OnSiteMiscellaneousCostsB { get; set; }

    public decimal? 諸経費A_GeneralExpensesA { get; set; }

    public decimal? 諸経費B_GeneralExpensesB { get; set; }
}