// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TI_積算集計ヘッダ_EstimatedAggregationHeader
{
    public int? 見積番号_QuotationNumber { get; set; }

    public string 作成者CD_CreatorCode { get; set; }

    public byte? 案_Plan { get; set; }

    public decimal? 労務単価A_LaborCostA { get; set; }

    public decimal? 労務単価B_LaborCostB { get; set; }

    public byte? 現場雑費FLG_ConstructionExpenseFlag { get; set; }

    public float? 現場雑費率_ConstructionExpenseRate { get; set; }

    public int? 現場雑費端数_ConstructionExpenseFraction { get; set; }

    public byte? 諸経費FLG_MiscellaneousExpenseFlag { get; set; }

    public float? 諸経費率_MiscellaneousExpenseRate { get; set; }

    public int? 諸経費端数_MiscellaneousExpenseFraction { get; set; }

    public byte? 雑材消耗FLG_MaterialConsumptionFlag { get; set; }

    public byte? 雑材A材B材_MaterialAAndB { get; set; }

    public float? 労務費基準_LaborCostStandard { get; set; }

    public byte? 労務費FLG_LaborCostFlag { get; set; }

    public bool? 労務費計算FLG_LaborCostCalculationFlag { get; set; }

    public byte? 付帯工事FLG_AdditionalWorkFlag { get; set; }
}