// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TI_積算表紙データ_EstimatedGeneralData
{
    public string 作成者CD_CreatorCode { get; set; }

    public int? 見積番号_QuotationNumber { get; set; }

    public string 表示見積番号_VisibleQuotationNumber { get; set; }

    public byte? 暦FLG_CalenderFlag { get; set; }

    public string 日付_Date { get; set; }

    public int? 提出先CD_SubmissionDestinationCode { get; set; }

    public string 提出先1_SubmissionDestination1 { get; set; }

    public string 提出先2_SubmissionDestination2 { get; set; }

    public byte? 敬称FLG_HonorificTitleFlag { get; set; }

    public string 敬称_HonorificTitle { get; set; }

    public decimal? 見積金額_QuotationAmount { get; set; }

    public decimal? 見積総額_TotalQuotationAmount { get; set; }

    public string 工事名称_ProjectName { get; set; }

    public string 工事名称1_ProjectName1 { get; set; }

    public string 工事名称2_ProjectName2 { get; set; }

    public byte? 都道府県CD_PrefectureCode { get; set; }

    public short? 市町村CD_CityCode { get; set; }

    public string 工事場所_ProjectSite { get; set; }

    public int? 発注者CD_ClientCode { get; set; }

    public string 発注者_Client { get; set; }

    public string 工期_ProjectDuration { get; set; }

    public string 有効期間_validityperiodOrDuration { get; set; }

    public byte? 支払条件FLG_PaymentTermsFlag { get; set; }

    public string 支払条件_PaymentTerms { get; set; }

    public string 特記事項1_SpecialNote1 { get; set; }

    public string 特記事項2_SpecialNote2 { get; set; }

    public string 特記事項3_SpecialNote3 { get; set; }

    public string 特記事項4_SpecialNote4 { get; set; }

    public string 特記事項5_SpecialNote5 { get; set; }

    public byte? 消費税FLG_SalesTaxFlag { get; set; }

    public float? 消費税率_SalesTaxRate { get; set; }

    public string 消費税_SalesTax { get; set; }

    public decimal? 消費税額_SalesTaxAmount { get; set; }

    public byte? 御社ネットFLG_CompanyNetworkFlag { get; set; }

    public decimal? 御社ネット金額_CompanyNetworkAmount { get; set; }

    public string 御社ネット_CompanyNetwork { get; set; }

    public byte? 諸経費FLG_MiscellaneousExpensesFlag { get; set; }

    public float? 諸経費率_MiscellaneousExpensesRate { get; set; }

    public decimal? 諸経費_MiscellaneousExpenses { get; set; }

    public byte? 出精値引FLG_DiscountFlag { get; set; }

    public decimal? 出精値引_SpecialDiscount { get; set; }

    public bool? 金抜きFLG_PriceExclusionFlag { get; set; }

    public string 特別項目_SpecialItem { get; set; }

    public decimal? 特別金額_SpecialAmount { get; set; }

    public string 内訳ヘッター_BreakdownHeader { get; set; }

    public byte? フッターFLG_FooterFlag { get; set; }

    public string 内訳フッター_BreakdownFooter { get; set; }

    public byte? 経費FLG1_ExpensesFlag1 { get; set; }

    public string 経費名1_ExpensesName1 { get; set; }

    public decimal? 経費1_Expense1 { get; set; }

    public byte? 経費FLG2_ExpenseFlag2 { get; set; }

    public string 経費名2_ExpenseName2 { get; set; }

    public decimal? 経費2_Expense2 { get; set; }

    public byte? 経費FLG3_ExpenseFlag3 { get; set; }

    public string 経費名3ExpensesName3 { get; set; }

    public decimal? 経費3_Expense3 { get; set; }

    public byte? 経費FLG4_ExpensesFlag4 { get; set; }

    public string 経費名4_ExpensesName4 { get; set; }

    public decimal? 経費4_Expenses4 { get; set; }

    public bool? 電線まとめFLG_CableSummaryFlag { get; set; }
}