// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TI_素材その他データMaterialAndAdditionalData
{
    public string 作成者CD_CreatorCode { get; set; }

    public int? 見積番号_QuotationNumber { get; set; }

    public short? 素材分類CD_MaterialCategoryCode { get; set; }

    public byte? ABC材_ABCMaterial { get; set; }

    public short? 表示順_DisplayOrder { get; set; }

    public string 素材分類名_MaterialCategoryName { get; set; }

    public float? その他率設定_OtherRateSetting { get; set; }
}