// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TI_複合表紙データ_CompositCoverData
{
    public string 作成者CD_CreatorCode { get; set; }

    public int? 見積番号_EstimationNumber { get; set; }

    public string 表示見積番号_DisplayedEstimationNumber { get; set; }

    public byte? 暦FLG_CalendarFlag { get; set; }

    public string 日付_Date { get; set; }

    public int? 提出先CD_SubmissionDestinationCode { get; set; }

    public string 提出先1_SubmissionDestination1 { get; set; }

    public string 提出先2_SubmissionDestination2 { get; set; }

    public byte? 敬称FLG_HonorificFlag { get; set; }

    public string 敬称_Honorific { get; set; }

    public decimal? 見積金額_EstimatedAmount { get; set; }

    public decimal? 見積総額_TotalEstimatedAmount { get; set; }

    public string 工事名称_ProjectName { get; set; }

    public string 工事名称1_ProjectName1 { get; set; }

    public string 工事名称2_ProjectName2 { get; set; }

    public byte? 都道府県CD_PrefectureCode { get; set; }

    public short? 市町村CD_CityTownVillageCode { get; set; }

    public string 工事場所_ProjectLocation { get; set; }

    public int? 発注者CD_OrdererCode { get; set; }

    public string 発注者_Orderer { get; set; }

    public string 工期_ConstructionPeriod { get; set; }

    public string 有効期間_ValidityPeriod { get; set; }

    public byte? 支払条件FLG_PaymentConditionFlag { get; set; }

    public string 支払条件_PaymentCondition { get; set; }

    public string 特記事項1_SpecialNotes1 { get; set; }

    public string 特記事項2_SpecialNotes2 { get; set; }

    public string 特記事項3_SpecialNotes3 { get; set; }

    public string 特記事項4_SpecialNotes4 { get; set; }

    public string 特記事項5_SpecialNotes5 { get; set; }

    public byte? 消費税FLG_ConsumptionTaxFlag { get; set; }

    public float? 消費税率_ConsumptionTaxRate { get; set; }

    public string 消費税_ConsumptionTax { get; set; }

    public decimal? 消費税額_ConsumptionTaxAmount { get; set; }

    public byte? 御社ネットFLG_YourCompanyNetFlag { get; set; }

    public decimal? 御社ネット金額_YourCompanyNetAmount { get; set; }

    public string 御社ネット_YourCompanyNet { get; set; }

    public byte? 諸経費FLG_MiscellaneousExpensesFlag { get; set; }

    public float? 諸経費率_MiscellaneousExpensesRate { get; set; }

    public decimal? 諸経費_MiscellaneousExpenses { get; set; }

    public byte? 出精値引FLG_SpecialDiscountFlag { get; set; }

    public decimal? 出精値引_SpecialDiscount { get; set; }

    public bool? 金抜きFLG_PricingExclusionFlag { get; set; }

    public string 特別項目_SpecialItem { get; set; }

    public decimal? 特別金額_SpecialAmount { get; set; }

    public string 内訳ヘッター_BreakdownHeader { get; set; }

    public byte? フッターFLG_FooterFlag { get; set; }

    public string 内訳フッター_BreakdownFooter { get; set; }

    public byte? 経費FLG1_ExpensesFlag1 { get; set; }

    public string 経費名1_ExpensesName1 { get; set; }

    public decimal? 経費1_Expenses1 { get; set; }

    public byte? 経費FLG2_ExpensesFlag2 { get; set; }

    public string 経費名2_ExpensesName2 { get; set; }

    public decimal? 経費2_Expenses2 { get; set; }

    public byte? 経費FLG3_ExpensesFlag3 { get; set; }

    public string 経費名3_ExpensesName3 { get; set; }

    public decimal? 経費3_Expenses3 { get; set; }

    public byte? 経費FLG4_ExpensesFlag4 { get; set; }

    public string 経費名4_ExpensesName4 { get; set; }

    public decimal? 経費4_Expenses4 { get; set; }
}