// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TI_複合集計ヘッダ_CompositeAggregationHeader
{
    public int? 見積番号_EstimationNumber { get; set; }

    public string 作成者CD_CreatorCode { get; set; }

    public byte? 案_Plan { get; set; }

    public decimal? 労務単価A_LaborUnitPriceA { get; set; }

    public decimal? 労務単価B_LaborUnitPriceB { get; set; }

    public decimal? 普作単価A_NormalOperationUnitPriceA { get; set; }

    public decimal? 普作単価B_NormalOperationUnitPriceB { get; set; }

    public byte? 共通仮設費FLG_CommonTemporaryConstructionCostsFlag { get; set; }

    public decimal? 共通仮設費A_CommonTemporaryConstructionCostsA { get; set; }

    public decimal? 共通仮設費B_CommonTemporaryConstructionCostsB { get; set; }

    public byte? 現場管理費FLG_SiteManagementCostsFlag { get; set; }

    public decimal? 現場管理費A_SiteManagementCostsA { get; set; }

    public decimal? 現場管理費B_SiteManagementCostsB { get; set; }

    public byte? 一般管理費FLG_GeneralAdministrativeCostsFlag { get; set; }

    public decimal? 一般管理費A_GeneralAdministrativeCostsA { get; set; }

    public decimal? 一般管理費B_GeneralAdministrativeCostsB { get; set; }

    public byte? 新営改修FLG_NewConstructionOrRenovationFlag { get; set; }

    public byte? 付帯工事FLG_AdditionalWorkFlag { get; set; }
}