// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TI_配線器具単価データ_WiringDeviceUintPriceData
{
    public int? 見積番号_EstimationNumber { get; set; }

    public string 作成者CD_CreatorCode { get; set; }

    public int? 工種番号_WorkTypeNumber { get; set; }

    public short? 部材番号_MaterialNumber { get; set; }

    public string 部材名_MaterialName { get; set; }

    public decimal? 提出単価_部品_SubmissionPrice_Parts { get; set; }

    public decimal? 提出単価_α_SubmissionPrice_Alpha { get; set; }

    public decimal? 提出単価_取付枠_SubmissionPrice_MountingFrame { get; set; }

    public decimal? 提出単価_プレート_SubmissionPrice_Plate { get; set; }

    public decimal? 社内単価_部品_InternalPrice_Parts { get; set; }

    public decimal? 社内単価_α_InternalPrice_Alpha { get; set; }

    public decimal? 社内単価_取付枠_InternalPrice_MountingFrame { get; set; }

    public decimal? 社内単価_プレート_InternalPrice_Plate { get; set; }

    public decimal? 販売定価_部品_SalesPrice_Parts { get; set; }

    public decimal? 販売定価_α_SalesPrice_Alpha { get; set; }

    public decimal? 販売定価_取付枠_SalesPrice_MountingFrame { get; set; }

    public decimal? 販売定価_プレート_SalesPrice_Plate { get; set; }

    public decimal? 原価率_部品_CostRate_Parts { get; set; }

    public decimal? 原価率_α_CostRate_Alpha { get; set; }

    public decimal? 原価率_取付枠_CostRate_MountingFrame { get; set; }

    public decimal? 原価率_プレート_CostRate_Plate { get; set; }

    public float? 歩掛_UnitRate { get; set; }

    public byte? ハンドルFLG_HandleFlag { get; set; }

    public bool? 絶縁枠FLG_InsulationFrameFlag { get; set; }

    public byte? プレートNo_PlateNumber { get; set; }

    public byte? プレート種類_PlateType { get; set; }

    public byte? 種別_Category { get; set; }
}