// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_メーカーマスタ_TM_MakerMaster
{
    public short? メーカーCD_ManufacturerCode { get; set; }

    public short? 表示順_DisplayOrder { get; set; }

    public string メーカー名_ManufacturerName { get; set; }

    public bool? 削除FLG_DeleteFlag { get; set; }
}