// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_ファンクション_TM_Functions
{
    public string Function01 { get; set; }

    public string Function02 { get; set; }

    public string Function03 { get; set; }

    public string Function04 { get; set; }

    public string Function05 { get; set; }

    public string Function06 { get; set; }

    public string Function07 { get; set; }

    public string Function08 { get; set; }

    public string Function09 { get; set; }

    public string Function10 { get; set; }
}