// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_ランクマスタ_TM_RankMaster
{
    public int? ランクCD_RankCode { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public string ランク名_RankName { get; set; }

    public float? 乗率_Multiplier { get; set; }

    public bool? 削除FLG_DeletionFlag { get; set; }
}