// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_変換歩掛名称マスタ_TM_ConversionWorkRateNameMaster
{
    public byte? 変換歩掛CD_ConversionWorkRateCode { get; set; }

    public string 変換歩掛名称_ConversionWorkRateName { get; set; }

    public string 略称_Abbreviation { get; set; }
}