// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_名称マスタ_TM_CompanyNameMaster
{
    public byte? 名称CD_NameCode { get; set; }

    public byte? 名称番号_NameNumber { get; set; }

    public short? 表示順_DisplayOrder { get; set; }

    public string 名称_Name { get; set; }
}