// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_変換塗装単価マスタ_TM_PaintingConversionUnitPriceMaster
{
    public short? 塗装CD_PaintCode { get; set; }

    public string 塗装名称_PaintName { get; set; }

    public decimal? 金額1_Amount1 { get; set; }

    public byte? 塗装FLG_PaintFlag { get; set; }
}