// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_役職マスタ_TM_JobMaster
{
    public short? 役職CD_PositionCode { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public string 役職名_PositionName { get; set; }

    public bool? 削除FLG_DeletionFlag { get; set; }
}