// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ComMS.Models;

public partial class TM_得意先マスタ_CustomerMaster
{
    [Key]
    public int 得意先CD_CustomerCode { get; set; }

    public int グループCD_GroupCode { get; set; }

    public int 表示順_DisplayOrder { get; set; }

    public string フリガナ_Furigana { get; set; }

    public string 得意先名_CustomerName { get; set; }

    public string 支社名_BranchName { get; set; }

    public string 郵便番号_PostalCode { get; set; }

    public int? 都道府県CD_PrefectureCode { get; set; }

    public string 都道府県名_PrefectureName { get; set; }

    public int? 市町村CD_CityCode { get; set; }

    public string 市町村名_CityName { get; set; }

    public string 住所1_Address1 { get; set; }

    public string 住所2_Address2 { get; set; }

    public string 電話番号1_PhoneNumber1 { get; set; }

    public string 電話番号2_PhoneNumber2 { get; set; }

    public DateTime? 締切日_ClosingDate { get; set; }

    public string ランク_Rank { get; set; }

    public string FAX1 { get; set; }

    public string FAX2 { get; set; }

    public string eメール_Email { get; set; }

    public string HPアドレス_HomepageAddress { get; set; }

    public string 担当者_PersonInCharge { get; set; }

    public int? 出力帳票形式1_OutputReportFormat1 { get; set; }

    public int? 出力帳票形式2_OutputReportFormat2 { get; set; }

    public bool? 請求初期FLG_InitialBillingFlag { get; set; }

    public bool? 積算初期FLG_InitialEstimationFlag { get; set; }

    public string 備考_Remarks { get; set; }
    public DateTimeOffset RegistrationDate { get; set; }
    public DateTimeOffset UpdateDate { get; set; }
}