// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_変換歩掛マスタ_TM_ConversionWorkRateMaster
{
    public double? 分類1_Category1 { get; set; }

    public double? 分類2_Category2 { get; set; }

    public double? 分類3_Category3 { get; set; }

    public double? 分類4_Category4 { get; set; }

    public byte? 変換歩掛CD_ConversionWorkRateCode { get; set; }

    public string 部材名_MaterialName { get; set; }

    public float? 歩掛_WorkRate { get; set; }
}