// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_支給区分マスタ_TM_PaymentClassificationMaster
{
    public short? 支給区分CD_ProvisionCategoryCode { get; set; }

    public short? 表示順_DisplayOrder { get; set; }

    public string 支給区分名_ProvisionCategoryName { get; set; }

    public float? 歩掛係数_WorkRateCoefficient { get; set; }

    public bool? 削除FLG_DeleteFlag { get; set; }
}