// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_歩掛補正マスタ_TM_WalkCorrectionMaster
{
    public short? 分類1_Category1 { get; set; }

    public short? 表示順_DisplayOrder { get; set; }

    public string 補助名_AuxiliaryName { get; set; }

    public byte? 補助FLG1_AuxiliaryFlag1 { get; set; }

    public byte? 補助FLG2_AuxiliaryFlag2 { get; set; }

    public bool? 削除FLG_DeletionFlag { get; set; }
}