// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_経費ランクマスタ_TM_ExpenseRankMaster
{
    public string ランクCD_RankCode { get; set; }

    public decimal? 労務単価A_LaborCostA { get; set; }

    public decimal? 労務単価B_LaborCostB { get; set; }

    public float? 現場雑費率_SiteMiscellaneousRate { get; set; }

    public float? 諸経費率_OtherExpensesRate { get; set; }
}