// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_特殊分類2マスタ_TM_SpecialClassification2Master
{
    public short? 分類1_Classification1 { get; set; }

    public short? 分類2_Classification2 { get; set; }

    public byte? 特殊CD_SpecialCode { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public string データ名_DataName { get; set; }

    public byte? 集計FLG_AggregationFlag { get; set; }

    public bool? 削除FLG_DeleteFlag { get; set; }

    public int? 標準単価_StandardUnitPrice { get; set; }
}