// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_素材マスタ_TM_MaterialMaster
{
    public int? 分類1_Category1 { get; set; }

    public int? 分類2_Category2 { get; set; }

    public int? 分類3_Category3 { get; set; }

    public int? 分類4_Category4 { get; set; }

    public string 素材CD_MaterialCode { get; set; }

    public string 分類名_CategoryName { get; set; }

    public string 部材名_PartName { get; set; }

    public decimal? 標準単価_StandardUnitPrice { get; set; }

    public decimal 提出単価_SubmissionUnitPrice { get; set; }

    public decimal? 社内単価_InternalUnitPrice { get; set; }

    public decimal? 建物単価_BuildingUnitPrice { get; set; }

    public decimal? 積資単価_AccumulatedUnitPrice { get; set; }

    public decimal? 複合単価_CompositeUnitPrice { get; set; }

    public decimal? 電設資材_ElectricalInstallationMaterial { get; set; }

    public decimal? 電設乗率_ElectricalInstallationRate { get; set; }

    public decimal? 電設原価率_ElectricalInstallationCostRate { get; set; }

    public decimal? 補給率_SupplyRate { get; set; }

    public decimal? 付属品率_AccessoryRate { get; set; }

    public decimal? 雑材率_MiscellaneousMaterialRate { get; set; }

    public int? 労務単価A_LaborUnitPriceA { get; set; }

    public decimal 歩掛A_WorkRateA { get; set; }

    public decimal? 撤去率A_RemovalRateA { get; set; }

    public int? 労務単価B_LaborUnitPriceB { get; set; }

    public decimal? 歩掛B_WorkRateB { get; set; }

    public decimal? 撤去率B_RemovalRateB { get; set; }

    public decimal? その他_Other { get; set; }

    public int? 単位CD_UnitCode { get; set; }

    public string 単位_Unit { get; set; }

    public int? 素材分類CD_MaterialCategoryCode { get; set; }

    public string 素材分類名_MaterialCategoryName { get; set; }

    public int? ABC材_ABC_Material { get; set; }

    public DateTime? 更新日付_UpdateDate { get; set; }

    public string 更新者_Updater { get; set; }

    public decimal? 天井開口費_CeilingOpeningCost { get; set; }
}