// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_素材分類ヘッダ_TM_MaterialClassificationHeader
{
    public byte? 分類番号_CategoryNumber { get; set; }

    public string 分類名_CategoryName { get; set; }
}