// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_補助マスタ_TM_Auxiliary_SupportMaster
{
    public short? 補助CD_SupportCode { get; set; }

    public short? 表示順_DisplayOrder { get; set; }

    public string 補助名_SupportName { get; set; }

    public byte? 補助FLG1_SupportFlag1 { get; set; }

    public byte? 補助FLG2_SupportFlag2 { get; set; }

    public bool? 削除FLG_DeleteFlag { get; set; }
}