// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_資格マスタ_TM_QualificationMaster
{
    public short? 資格CD_QualificationCode { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public string 資格名_QualificationName { get; set; }

    public bool? 削除FLG_DeleteFlag { get; set; }
}