// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_都道府県マスタ_TM__StateandProvinceMaster
{
    public byte? 都道府県CD_PrefectureCode { get; set; }

    public string 都道府県名_PrefectureName { get; set; }

    public byte? 都道府県分類_PrefectureCategory { get; set; }

    public bool? 削除フラグ_DeleteFlag { get; set; }
}