// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_電工マスタ_TM_ElectricianMaster
{
    public short? 電工CD_ElectricianCode { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public string 氏名_FullName { get; set; }

    public decimal? 労務単価_LaborUnitPrice { get; set; }

    public DateTime? 生年月日_DateOfBirth { get; set; }

    public DateTime? 入社年月日_JoinDate { get; set; }

    public string 資格1_Qualification1 { get; set; }

    public string 資格2_Qualification2 { get; set; }

    public string 資格3_Qualification3 { get; set; }

    public string 役職_Position { get; set; }

    public string 郵便番号_PostCode { get; set; }

    public string 住所1_AddressLine1 { get; set; }

    public string 住所2_AddressLine2 { get; set; }

    public string 電話番号1_PhoneNumber1 { get; set; }

    public string 電話番号2_PhoneNumber2 { get; set; }

    public string 携帯電話1_MobilePhone1 { get; set; }

    public string 携帯電話2_MobilePhone2 { get; set; }

    public bool? 削除FLG_DeleteFlag { get; set; }
}