// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TR_内訳集計データ_ItemizedSummaryData
{
    public int? 表示順_DisplayOrder { get; set; }

    public short? 工種番号_ConstructionTypeNumber { get; set; }

    public byte? GP番号_GPNumber { get; set; }

    public string 品名及び名称_ProductAndName { get; set; }

    public string 項目_Item { get; set; }

    public string 形状寸法_ShapeDimensions { get; set; }

    public float? 数量_Quantity { get; set; }

    public float? 補給率_ReplenishmentRate { get; set; }

    public float? 提出数量_QuotationQuantity { get; set; }

    public float? NETRate_NET率 { get; set; }

    public float? 社内数量_InHouseQuantity { get; set; }

    public string 単位_Unit { get; set; }

    public string 支給区分名_PaymentCategoryName { get; set; }

    public decimal? 単価_UnitPrice { get; set; }

    public float? 乗率_LoadingRate { get; set; }

    public decimal? 提出単価_QuotationUnitPrice { get; set; }

    public float? 原価率_CostRate { get; set; }

    public decimal? 社内単価_InternalUnitPrice { get; set; }

    public float? 歩掛_WorkRate { get; set; }

    public float? 雑材消耗率_MaterialConsumptionRate { get; set; }

    public decimal? 提出金額_QuotationAmount { get; set; }

    public decimal? 社内金額_InHouseAmount { get; set; }

    public short? 素材分類CD_MaterialCategoryCode { get; set; }

    public string 素材分類名_MaterialCategoryName { get; set; }

    public bool? 改頁FLG_PageBreakFlag { get; set; }
}