// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TR_分類別集計データ_TR_CategorywiseSummaryData
{
    public int? 見積番号_QuotationNumber { get; set; }

    public string 作成者CD_CreatorCode { get; set; }

    public int? 工種番号_WorkTypeNumber { get; set; }

    public short? 部材番号_MaterialNumber { get; set; }

    public byte? 分類FLG_CategoryFlag { get; set; }

    public byte? 工種FLG_WorkTypeFlag { get; set; }

    public byte? 工種Child_WorkTypeChild { get; set; }

    public byte? 部材FLG_MaterialFlag { get; set; }

    public string 品名及び名称_ItemAndName { get; set; }

    public string 項目_Item { get; set; }

    public string 形状寸法_Dimensions { get; set; }

    public float? 数量_Quantity { get; set; }

    public float? 補給率_SupplyRate { get; set; }

    public float? 提出数量_SubmittedQuantity { get; set; }

    public float? NET率_NETRate { get; set; }

    public float? 社内数量_InternalQuantity { get; set; }

    public short? 単位CD_UnitCode { get; set; }

    public string 単位_Unit { get; set; }

    public short? 支給区分CD_SupplyCategoryCode { get; set; }

    public string 支給区分名_SupplyCategoryName { get; set; }

    public decimal? 単価_UnitPrice { get; set; }

    public float? 乗率_LoadRate { get; set; }

    public decimal? 提出単価_SubmittedUnitPrice { get; set; }

    public float? 原価率_CostRate { get; set; }

    public decimal? 社内単価_InternalUnitPrice { get; set; }

    public float? 歩掛_ManHours { get; set; }

    public float? 雑材消耗率_MiscellaneousMaterialConsumptionRate { get; set; }

    public decimal? 提出金額_SubmittedAmount { get; set; }

    public decimal? 社内金額_InternalAmount { get; set; }

    public short? 素材分類CD_MaterialCategoryCode { get; set; }

    public string 素材分類名_MaterialCategoryName { get; set; }
}