// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TR_内訳明細データ_DetailedBreakdownData
{
    public int? GP番号 { get; set; }

    public int? 表示順 { get; set; }

    public short? No { get; set; }

    public int? 工種番号 { get; set; }

    public short? 部材番号 { get; set; }

    public string 表示工種番号 { get; set; }

    public string 工種名 { get; set; }

    public string 部材名1 { get; set; }

    public string 部材名2 { get; set; }

    public float? 数量 { get; set; }

    public string 単位 { get; set; }

    public decimal? 単価 { get; set; }

    public decimal? 金額 { get; set; }

    public string 備考 { get; set; }

    public bool? 合計フラグ { get; set; }
}