// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TR_比較表データ_ComparisonTableData
{
    public int? 表示順_DisplayOrder { get; set; }

    public int? ＧP番号_GPNumber { get; set; }

    public string 頁番号_PageNumber { get; set; }

    public string 部材名_MaterialName { get; set; }

    public float? 数量_Quantity { get; set; }

    public decimal? 単価_UnitPrice { get; set; }

    public decimal? 金額_Amount { get; set; }

    public string 補助_Support { get; set; }

    public decimal? 単価1_UnitPrice1 { get; set; }

    public decimal? 金額1_Amount1 { get; set; }

    public string 製作所名1_ManufacturerName1 { get; set; }

    public decimal? 単価2_UnitPrice2 { get; set; }

    public decimal? 金額2_Amount2 { get; set; }

    public string 製作所名2_ManufacturerName2 { get; set; }

    public decimal? 単価3_UnitPrice3 { get; set; }

    public decimal? 金額3_Amount3 { get; set; }

    public string 製作所名3_ManufacturerName3 { get; set; }

    public string 採用製作所名_SelectedManufacturerName { get; set; }

    public byte? 掛率_DiscountRate { get; set; }

    public bool? 合計フラグ_TotalFlag { get; set; }
}