// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TR_素材乗率データ_MaterialLoadingRateData
{
    public byte? GP番号1_GPNumber1 { get; set; }

    public short? 表示順1_DisplayOrder1 { get; set; }

    public string 素材分類名1_MaterialCategoryName1 { get; set; }

    public float? 乗率設定1_LoadingRateSetting1 { get; set; }

    public float? 原価率設定1_CostRateSetting1 { get; set; }

    public short? 表示順2_DisplayOrder2 { get; set; }

    public string 素材分類名2_MaterialCategoryName2 { get; set; }

    public float? 乗率設定2_LoadingRateSetting2 { get; set; }

    public float? 原価率設定2_CostRateSetting2 { get; set; }

    public short? 表示順3_DisplayOrder3 { get; set; }

    public string 素材分類名3_MaterialCategoryName3 { get; set; }

    public float? 乗率設定3_LoadingRateSetting3 { get; set; }

    public float? 原価率設定3_CostRateSetting3 { get; set; }
}