// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TR_複合総括データ_CompositeSummaryData
{
    public int? 見積番号_QuotationNumber { get; set; }

    public string 作成者CD_AuthorCode { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public byte? GP番号_GPNumber { get; set; }

    public string 工事種目_ConstructionItem { get; set; }

    public decimal? B材_A_MaterialB_A { get; set; }

    public decimal? 電線類_A_Wires_A { get; set; }

    public decimal? A材_A_MaterialA_A { get; set; }

    public decimal? 防災_A_DisasterPrevention_A { get; set; }

    public decimal? 雑材_A_MiscellaneousMaterials_A { get; set; }

    public decimal? 付帯工事_A_AuxiliaryWork_A { get; set; }

    public decimal? 労務費_A_LaborCost_A { get; set; }

    public decimal? 共通費_A_CommonCost_A { get; set; }

    public decimal? 経費等_A_ExpensesEtc_A { get; set; }

    public decimal? 小計_A_Subtotal_A { get; set; }

    public decimal? B材_B_MaterialB_B { get; set; }

    public decimal? 電線類_B_Wires_B { get; set; }

    public decimal? A材_B_MaterialA_B { get; set; }

    public decimal? 防災_B_DisasterPrevention_B { get; set; }

    public decimal? 雑材_B_MiscellaneousMaterials_B { get; set; }

    public decimal? 付帯工事_B_AuxiliaryWork_B { get; set; }

    public decimal? 労務費_B_LaborCost_B { get; set; }

    public decimal? 共通費_B_CommonCost_B { get; set; }

    public decimal? 経費等_B_ExpensesEtc_B { get; set; }

    public decimal? 小計_B_Subtotal_B { get; set; }
}