// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TR_複合印刷データ_CompositePrintData
{
    public int? 見積番号_QuotationNumber { get; set; }

    public string 作成者CD_AuthorCode { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public byte? GP番号_GPNumber { get; set; }

    public short? 工種番号_ConstructionTypeNumber { get; set; }

    public byte? 分類FLG_CategoryFlag { get; set; }

    public byte? 工種FLG_ConstructionTypeFlag { get; set; }

    public byte? 工種Child_ConstructionTypeChild { get; set; }

    public short? 部材FLG_MaterialFlag { get; set; }

    public string 品名及び名称_ProductAndName { get; set; }

    public string 項目_Item { get; set; }

    public string 形状寸法_ShapeAndDimension { get; set; }

    public float? 数量_Quantity { get; set; }

    public float? 補給率_SupplyRate { get; set; }

    public float? 提出数量_QuotationQuantity { get; set; }

    public float? NET率_NETRate { get; set; }

    public float? 社内数量_InHouseQuantity { get; set; }

    public short? 単位CD_UnitCode { get; set; }

    public string 単位_Unit { get; set; }

    public short? 支給区分CD_SupplyDivisionCode { get; set; }

    public string 支給区分名_SupplyDivisionName { get; set; }

    public byte? 単価計算FLG_UnitPriceCalculationFlag { get; set; }

    public decimal? 単価_UnitPrice { get; set; }

    public float? 乗率_LoadRate { get; set; }

    public decimal? 提出単価_QuotationUnitPrice { get; set; }

    public float? 原価率_CostRate { get; set; }

    public decimal? 社内単価_InternalUnitPrice { get; set; }

    public float? 歩掛_LaborRate { get; set; }

    public float? 雑材消耗率_MiscellaneousMaterialConsumptionRate { get; set; }

    public decimal? 提出金額_QuotationAmount { get; set; }

    public decimal? 社内金額_InternalAmount { get; set; }

    public short? 素材分類CD_MaterialCategoryCode { get; set; }

    public string 素材分類名_MaterialCategoryName { get; set; }
}