// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ComMS.Models;

public partial class TW_基礎データ_BasicData
{
    [Key]
    public int 身分証明書_ID { get; set; }
    public string 作成者CD_CreatorCode { get; set; }

    public int? 見積番号_QuotationNumber { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public string 表示見積番号_DisplayQuotationNumber { get; set; }

    public DateTimeOffset? 日付_Date { get; set; }

    public string 工事名称1_ConstructionName1 { get; set; }

    public string 工事名称2_ConstructionName2 { get; set; }

    public int? 提出先CD_QuotationDestinationCode { get; set; }

    public string 提出先1_QuotationDestination1 { get; set; }

    public string 提出先2_QuotationDestination2 { get; set; }

    public string 作成者名_CreatorName { get; set; }

    public int? 積算複合FLG_EstimationCompositeFlag { get; set; }
}