// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TW_工種データ_ConstructionTypeData
{
    public int? 見積番号_QuotationNumber { get; set; }

    public string 作成者CD_CreatorCode { get; set; }

    public short? 工種番号_ConstructionTypeNumber { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public byte? 工種FLG_ConstructionTypeFlag { get; set; }

    public short? 工種枝1_ConstructionTypeBranch1 { get; set; }

    public short? 工種枝2_ConstructionTypeBranch2 { get; set; }

    public short? 工種枝3_ConstructionTypeBranch3 { get; set; }

    public byte? 工種Child_ConstructionTypeChild { get; set; }

    public int? 工種CD_WorkTypeCode { get; set; }

    public string 工種名_ConstructionTypeName { get; set; }

    public decimal? 金額_Amount { get; set; }

    public DateTime? 作成日付_CreationDate { get; set; }

    public DateTime? 更新日付_UpdateDate { get; set; }

    public string 備考_Remarks { get; set; }
}