// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TW_比較データ_ComparisonData
{
    public int? 見積番号_EstimateNumber { get; set; }

    public short? 工種番号_WorkTypeNumber { get; set; }

    public short? 部材番号_MaterialNumber { get; set; }

    public string 作成者CD_CreatorCode { get; set; }

    public byte? Group番号_GroupNumber { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public string 部材名_MaterialName { get; set; }

    public decimal? 単価1_UnitPrice1 { get; set; }

    public decimal? 単価2_UnitPrice2 { get; set; }

    public decimal? 単価3_UnitPrice3 { get; set; }

    public float? 乗率_RateOfIncrease { get; set; }

    public float? 原価率_CostRate { get; set; }

    public decimal? 提出単価_SubmittedUnitPrice { get; set; }

    public decimal? 社内単価_InternalUnitPrice { get; set; }

    public decimal? 提出金額_SubmittedAmount { get; set; }

    public decimal? 社内金額_InternalAmount { get; set; }

    public bool? 選択FLG_SelectionFlag { get; set; }
}