// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TW_複合率設定データ_CompositeRateSettingData
{
    public int? 工種番号_ConstructionTypeCode { get; set; }

    public short? 部材番号_MaterialCode { get; set; }

    public byte? 案_Plan { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public string 品名及び名称_ItemNameAndDescription { get; set; }

    public float? 補給率_SupplyRate { get; set; }

    public float? 付属品率_AccessoryRate { get; set; }

    public float? 雑材消耗率_MiscellaneousMaterialConsumptionRate { get; set; }

    public float? 歩掛A_WorkRateA { get; set; }

    public bool? 選択FLG_SelectionFlag { get; set; }
}