// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TW_複合集計データ_CompositeAggregationData
{
    public int? 見積番号_EstimateNumber { get; set; }

    public string 作成者CD_CreatorCode { get; set; }

    public int? 工種番号_WorkTypeCode { get; set; }

    public short? 部材番号_MaterialCode { get; set; }

    public byte? 案_Plan { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public byte? 分類FLG_ClassFlag { get; set; }

    public byte? 工種FLG_WorkTypeFlag { get; set; }

    public byte? 工種Child_WorkTypeChild { get; set; }

    public short? 部材FLG_MaterialFlag { get; set; }

    public string 品名及び名称_ItemNameAndDescription { get; set; }

    public string 項目_Item { get; set; }

    public string 形状寸法_Dimension { get; set; }

    public float? 数量_Quantity { get; set; }

    public short? 単位CD_UnitCode { get; set; }

    public string 単位_Unit { get; set; }

    public short? 支給区分CD_SupplyCategoryCode { get; set; }

    public string 支給区分名_SupplyCategoryName { get; set; }

    public float? 補給率_SupplyRate { get; set; }

    public float? 付属品率_AccessoryRate { get; set; }

    public float? 雑材消耗率_MiscellaneousMaterialConsumptionRate { get; set; }

    public float? その他_Others { get; set; }

    public byte? 単価計算FLG_PriceCalculationFlag { get; set; }

    public decimal? 単価_Price { get; set; }

    public float? 乗率_Multiplier { get; set; }

    public float? 原価率_CostRate { get; set; }

    public decimal? 提出単価_SubmittedPrice { get; set; }

    public decimal? 社内単価_InternalPrice { get; set; }

    public decimal? 複合単価A_CompositePriceA { get; set; }

    public decimal? 複合単価B_CompositePriceB { get; set; }

    public float? 歩掛A_WorkRateA { get; set; }

    public float? 歩掛B_WorkRateB { get; set; }

    public decimal? 電工単価_ElectricalWorkPrice { get; set; }

    public decimal? 普作単価_StandardWorkPrice { get; set; }

    public bool? 比較表FLG_ComparisonTableFlag { get; set; }

    public float? 塗装係数_PaintingCoefficient { get; set; }

    public float? 天井開口係数_CeilingOpeningCoefficient { get; set; }

    public decimal? 提出金額_SubmittedAmount { get; set; }

    public decimal? 社内金額_InternalAmount { get; set; }

    public short? 素材分類CD_MaterialCategoryCode { get; set; }

    public string 素材分類名_MaterialCategoryName { get; set; }

    public byte? ABC材_ABCMaterial { get; set; }
}