// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TW_見積一覧ワーク_WorkQuotationSummary
{
    public string 作成者CD_CreatorCode { get; set; }

    public int? 見積番号_QuotationNumber { get; set; }

    public string 表示見積番号_DisplayQuotationNumber { get; set; }

    public string 提出先_QuotationDestination { get; set; }

    public string 提出先1_QuotationDestination1 { get; set; }

    public string 提出先2_QuotationDestination2 { get; set; }

    public string 工事名称_ProjectName { get; set; }

    public string 作成者_Creator { get; set; }

    public string 仕入先_Supplier { get; set; }
}