// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TW_部材データ_MaterialsData
{
    public int? 見積番号_EstimateNumber { get; set; }

    public int? 工種番号_WorkTypeNumber { get; set; }

    public int? 部材番号_MaterialNumber { get; set; }

    public string 作成者CD_CreatorCode { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public byte? 部材FLG_MaterialFlag { get; set; }

    public int? 分類1_Category1 { get; set; }

    public int? 分類2_Category2 { get; set; }

    public int? 分類3_Category3 { get; set; }

    public int? 分類4_Category4 { get; set; }

    public int? 分類5_Category5 { get; set; }

    public int? 分類6_Category6 { get; set; }

    public int? 分類7_Category7 { get; set; }

    public int? 分類8_Category8 { get; set; }

    public string 部材名_MaterialName { get; set; }

    public string 部材名1_MaterialName1 { get; set; }

    public string 部材名2_MaterialName2 { get; set; }

    public string 部材名3_MaterialName3 { get; set; }

    public string 部材名4_MaterialName4 { get; set; }

    public string 部材名5_MaterialName5 { get; set; }

    public string 部材名6_MaterialName6 { get; set; }

    public string 部材名7_MaterialName7 { get; set; }

    public string 部材名8_MaterialName8 { get; set; }

    public float? 数量_Quantity { get; set; }

    public decimal? 金額_Amount { get; set; }

    public string 単位_Unit { get; set; }

    public decimal? 標準単価_StandardUnitPrice { get; set; }

    public decimal? 提出単価_SubmittedUnitPrice { get; set; }

    public decimal? 社内単価_InternalUnitPrice { get; set; }

    public decimal? 複合単価_CompositeUnitPrice { get; set; }

    public float? 補給率_ReplacementRate { get; set; }

    public float? 付属品率_AccessoryRate { get; set; }

    public float? 雑材率_MiscellaneousMaterialRate { get; set; }

    public int? 労務単価A_LaborUnitPriceA { get; set; }

    public float? 歩掛A_LaborCostA { get; set; }

    public float? 撤去率A_RemovalRateA { get; set; }

    public int? 労務単価B_LaborUnitPriceB { get; set; }

    public float? 歩掛B_LaborCostB { get; set; }

    public float? 撤去率B_RemovalRateB { get; set; }

    public float? その他_Other { get; set; }

    public decimal? 材料費小計_MaterialCostSubtotal { get; set; }

    public decimal? 労務費小計_LaborCostSubtotal { get; set; }

    public decimal? 複合単価小計_CompositeUnitPriceSubtotal { get; set; }

    public byte? 補助FLG_AssistanceFlag { get; set; }

    public string 補助_Assistance { get; set; }

    public byte? 入力FLG_InputFlag { get; set; }
}