// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class T_ErrorList
{
    public int ID { get; set; }

    public string ModuleName { get; set; }

    public string ProcedureName { get; set; }

    public int? Err_Number { get; set; }

    public string Err_Source { get; set; }

    public string Err_Description { get; set; }

    public DateTime? Err_Date { get; set; }
}