// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class T_TablePath
{
    public short? ID { get; set; }

    public string DbName { get; set; }

    public string OldTableName { get; set; }

    public string NewTableName { get; set; }

    public string Path { get; set; }

    public string Comment { get; set; }

    public byte? FLG { get; set; }

    public bool? Use { get; set; }
}