// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ComMS.Models;

public partial class TC_ユーザ情報_TC_UserInformation 
{
    
    public Guid UserCD { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public string 部署CD_DepartmentCode { get; set; }

    public string UserWinID { get; set; }


    public int? 見積番号_QuotationNumber { get; set; }

    public int? 請求番号_InvoiceNumber { get; set; }

    public int? 権限_Permissions { get; set; }

    public bool? 有効無効_EnabledDisabled { get; set; }

    public decimal? 労務単価_LaborUnitPrice { get; set; }

    public string Initial { get; set; }
}

public class ApplicationUser : IdentityUser<Guid>
{
    
}