// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TI_基礎データ_BasicData
{
    public string 作成者CD_CreatorCode { get; set; }

    public int? 見積番号_QuotationNumber { get; set; }

    public string 表示見積番号_ShowQuotationNumber { get; set; }

    public DateTime? 日付_Date { get; set; }

    public string 工事名称1_ConstructionProjectName1 { get; set; }

    public string 工事名称2_ProjectName2 { get; set; }

    public byte? 都道府県CD_PrefectureCode { get; set; }

    public int? 市町村CD_CityCode { get; set; }

    public string 工事場所_ConstructionProjectSite { get; set; }

    public int? 提出先CD_SubmissionDestinationCode { get; set; }

    public string 提出先1_SubmissionAddress1 { get; set; }

    public string 提出先2_SubmissionAddress2 { get; set; }

    public int? 発注者CD_ClientCode { get; set; }

    public string 発注者_Client { get; set; }

    public string 仕入先_Vendor { get; set; }

    public string ランクCD_LevelCode { get; set; }

    public decimal? 労務単価A_LaborUnitPriceA { get; set; }

    public decimal? 労務単価B_LaborUnitPriceB { get; set; }

    public byte? 現場雑費FLG_SiteMiscellaneousExpensesFlag { get; set; }

    public float? 現場雑費率_SiteMiscellaneousExpenseRate { get; set; }

    public byte? 現場雑費端数_SiteMiscellaneousExpenseRounding { get; set; }

    public byte? 諸経費FLG_MiscellaneousExpensesFlag { get; set; }

    public float? 諸経費率_MiscellaneousExpenseRate { get; set; }

    public decimal? 諸経費_MiscellaneousExpenses { get; set; }

    public byte? 諸経費端数_MiscellaneousExpenseRounding { get; set; }

    public float? 電線管NET率_ElectricalConduitNETRate { get; set; }

    public float? 電線管補給率_ConduitSupplyRate { get; set; }

    public float? 電線類NET率_WireNETRate { get; set; }

    public float? 電線類補給率_WireSupplyRate { get; set; }

    public byte? 電線計算単位_WireCalculationRate { get; set; }

    public byte? 単価計算基準_UnitPriceCalculationStandard { get; set; }

    public byte? 歩掛計算基準_LaborCostCalculationStandard { get; set; }

    public byte? 雑材消耗FLG_MiscellaneousMaterialConsumptionFlag { get; set; }

    public float? 労務費基準_LaborCostStandard { get; set; }

    public byte? 雑材A材B材_MiscellaneousMaterialsAandB { get; set; }

    public byte? 労務費FLG_LaborCostFlag { get; set; }

    public bool? 労務費計算FLG_LaborCostCalculationFlag { get; set; }

    public byte? 付帯工事FLG_associatedconstructionwork { get; set; }

    public int? ケーブルFLG_CableFlag { get; set; }

    public int? ケーブル係数FLG_CableCoefficientFlag { get; set; }

    public float? ケーブル係数_CableCoefficient { get; set; }

    public byte? Cラック付属品FLG_CRackAccessoriesFlag { get; set; }

    public float? Cラック付属品係数_CRackAccessoriesCoefficient { get; set; }

    public byte? Cラック支持材FLG_CRackSupportMaterialFlag { get; set; }

    public float? Cラック支持材係数_CRackSupportMaterialCoefficient { get; set; }

    public byte? RW付属品FLG_RWAccessoriesFlag { get; set; }

    public float? RW付属品係数_RWAccessoriesCoefficient { get; set; }

    public byte? RW支持材FLG_RWSupportMaterialFlag { get; set; }

    public float? RW支持材係数_RWSupportMaterialCoefficient { get; set; }

    public int? 照明取付FLG_LightingInstallationFlag { get; set; }

    public int? 照明取付係数FLG_LightingInstallationCoefficientFlag { get; set; }

    public float? 照明取付係数_LightingInstallationCoefficient { get; set; }

    public int? 盤取付FLG_PanelInstallationFlag { get; set; }

    public int? 盤取付係数FLG_PanelInstallationCoefficientFlag { get; set; }

    public float? 盤取付係数_PanelInstallationCoefficient { get; set; }

    public int? 配管係数FLG_PipingCoefficientFlag { get; set; }

    public float? 配管係数1_PipingCoefficient1 { get; set; }

    public float? 配管係数2_PipingCoefficient2 { get; set; }

    public float? 付帯工事乗率_AncillaryConstructionRate { get; set; }

    public float? 付帯工事原価率_AncillaryConstructionCostRate { get; set; }

    public float? 共通費乗率_CommonExpenseRatio { get; set; }

    public float? 共通費原価率_CommonCostRate { get; set; }

    public int? 乗率分類番号_RateCategoryNumber { get; set; }

    public byte? 積算複合FLG_AccumulationCompositFlag { get; set; }

    public bool? 工種部材変更FLG_S_WorkTypeMaterialChangeFlag_S { get; set; }

    public bool? 工種部材変更FLG_F_WorkTypeMaterialChangeFlag_F { get; set; }

    public decimal? 電工労務単価A_ElectricianlaborunitpriceA { get; set; }

    public decimal? 電工労務単価B_ELectricianlaborunitpriceB { get; set; }

    public decimal? 普作労務単価A_GenerallaborunitpriceA { get; set; }

    public decimal? 普作労務単価B_GenerallaborunitpriceA { get; set; }

    public decimal? 見積金額_QuotationAmount { get; set; }

    public byte? 採用案No_AdoptedPlanNumber { get; set; }

    public DateTime? 作成日付_CreationDate { get; set; }

    public DateTime? 更新日付_DateUpdated { get; set; }

    public string 用途_Use { get; set; }

    public string 建物構造_BuildingStructure { get; set; }

    public byte? 塔屋_TowerBuilding { get; set; }

    public byte? 地上_AboveGround { get; set; }

    public byte? 地下_UnderGround { get; set; }

    public byte? 戸数_NumberOfUnits { get; set; }

    public float? 延床面積_TotalFloorArea { get; set; }

    public float? 基準床面積_ReferenceFloorArea { get; set; }

    public float? EPS合計面積_ExpandedPolystyreneTotalArea { get; set; }

    public string 備考_Remarks { get; set; }
}