// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TI_比較基本データ_ComparisonBasicData
{
    public int? 見積番号_QuotationNumber { get; set; }

    public short? 工種番号_ConstructionTypeNumber { get; set; }

    public short? 部材番号_MaterialNumber { get; set; }

    public string 作成者CD_CreatorCode { get; set; }

    public string 製作所名1_ManufacturerName1 { get; set; }

    public string 製作所名2_ManufacturerName2 { get; set; }

    public string 製作所名3_ManufacturerName3 { get; set; }

    public string 採用製作所名_ApprovedManufacturerName { get; set; }

    public byte? 掛率_MarkUpRate { get; set; }

    public decimal? 金額_AmountOfdecimal { get; set; }

    public string 頁_Page { get; set; }
}