// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TI_比較GP名データ_ComparisonGroupNameData
{
    public int? 見積番号_QuotationNumber { get; set; }

    public string 作成者CD_CreatorCode { get; set; }

    public short? GPCD_GPCode { get; set; }

    public short? 表示順_DisplaySequence { get; set; }

    public string GP名_GPName { get; set; }

    public bool? 選択FLG_ChoiceFlag { get; set; }

    public short? 仕入先CD1_VendorCode1 { get; set; }

    public short? 仕入先CD2_VendorCode2 { get; set; }

    public short? 仕入先CD3_VendorCode3 { get; set; }

    public short? 採用仕入先CD_ApprovedVendorCode { get; set; }
}