// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ComMS.Models;

public partial class TI_積算集計データ_EstimatedAggregationData
{
    [Key]
    public int Id { get; set; }
    public int? 見積番号_QuotationNumber { get; set; }

    public string 作成者CD_CreatorCode { get; set; }

    public int? 工種番号_ConstructionTypeNumber { get; set; }

    public int? 部材番号_MaterialNumber { get; set; }

    public byte? 案_Proposal { get; set; }

    public int? 表示順_DisplaySequence { get; set; }

    public byte? 分類FLG_CategoryFlag { get; set; }

    public byte? 工種FLG_ConstructionTypeFlag { get; set; }

    public byte? 工種Child_ConstructionTypeChild { get; set; }

    public int? 部材FLG_MaterialFlag { get; set; }

    public string 品名及び名称_ItemNameAndDescription { get; set; }

    public string 項目_Item { get; set; }

    public string 形状寸法_ShapeAndDimension { get; set; }

    public decimal? 数量_Quantity { get; set; }

    public decimal? 補給率_SupplyRate { get; set; }

    public decimal? 提出数量_SubmittedQuantity { get; set; }

    public decimal? NET率_NETRate { get; set; }

    public decimal? 社内数量_InHouseQuantity { get; set; }

    public decimal? 付属品率_AccessoryRate { get; set; }

    public int? 単位CD_UnitCode { get; set; }

    public string 単位_Unit { get; set; }

    public int? 支給区分CD_SupplyClassificationCode { get; set; }

    public string 支給区分名_SupplyClassificationName { get; set; }

    public byte? 単価計算FLG_UnitPriceCalculationFlag { get; set; }

    public decimal? 単価_UnitPrice { get; set; }

    public decimal? 乗率_RateMultiplier { get; set; }

    public decimal? 提出単価_SubmittedUnitPrice { get; set; }

    public decimal? 原価率_CostRate { get; set; }

    public decimal? 社内単価_InHouseUnitPrice { get; set; }

    public decimal? 歩掛_WorkRate { get; set; }

    public decimal? 雑材消耗率_MiscellaneousMaterialConsumptionRate { get; set; }

    public decimal? 塗装係数_PaintingCoefficient { get; set; }

    public decimal? 天井開口係数_CeilingOpeningCoefficient { get; set; }

    public decimal? 提出金額_SubmittedAmount { get; set; }

    public decimal? 社内金額_InHouseAmount { get; set; }

    public int? 素材分類CD_MaterialClassificationCode { get; set; }

    public string 素材分類名_MaterialClassificationName { get; set; }

    public byte? ABC材_ABCMaterials { get; set; }
}