// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TI_複合集計データ_CompositAggregationData
{
    public int? 見積番号 { get; set; }

    public string 作成者CD { get; set; }

    public int? 工種番号 { get; set; }

    public short? 部材番号 { get; set; }

    public byte? 案 { get; set; }

    public int? 表示順 { get; set; }

    public byte? 分類FLG { get; set; }

    public byte? 工種FLG { get; set; }

    public byte? 工種Child { get; set; }

    public short? 部材FLG { get; set; }

    public string 品名及び名称 { get; set; }

    public string 項目 { get; set; }

    public string 形状寸法 { get; set; }

    public float? 数量 { get; set; }

    public short? 単位CD { get; set; }

    public string 単位 { get; set; }

    public short? 支給区分CD { get; set; }

    public string 支給区分名 { get; set; }

    public float? 補給率 { get; set; }

    public float? 付属品率 { get; set; }

    public float? 雑材消耗率 { get; set; }

    public float? その他 { get; set; }

    public byte? 単価計算FLG { get; set; }

    public decimal? 単価 { get; set; }

    public float? 乗率 { get; set; }

    public float? 原価率 { get; set; }

    public decimal? 提出単価 { get; set; }

    public decimal? 社内単価 { get; set; }

    public decimal? 複合単価A { get; set; }

    public decimal? 複合単価B { get; set; }

    public float? 歩掛A { get; set; }

    public float? 歩掛B { get; set; }

    public decimal? 電工単価 { get; set; }

    public decimal? 普作単価 { get; set; }

    public bool? 比較表FLG { get; set; }

    public float? 塗装係数 { get; set; }

    public float? 天井開口係数 { get; set; }

    public decimal? 提出金額 { get; set; }

    public decimal? 社内金額 { get; set; }

    public short? 素材分類CD { get; set; }

    public string 素材分類名 { get; set; }

    public byte? ABC材 { get; set; }
}