// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TI_配線器具個数データ_WiringDeviceQuantityData
{
    public int? 見積番号_QuotationNumber { get; set; }

    public string 作成者CD_CreatorCode { get; set; }

    public int? 工種番号_WorkTypeNumber { get; set; }

    public short? 部材番号_MaterialNumber { get; set; }

    public byte? 配線器具種別_WiringDeviceType { get; set; }

    public short? 配線分類CD_WiringClassificationCode { get; set; }

    public string 配線分類名称_WiringClassificationName { get; set; }

    public byte? 数量_Quantity { get; set; }
}