// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ComMS.Models;

public partial class TI_部材データ_MaterialsData
{
    [Key]
    public int Id { get; set; }
    public int? 見積番号_QuotationNumber { get; set; }

    public string 作成者CD_CreatorCode { get; set; }

    public int? 工種番号_ConstructionTypeNumber { get; set; }

    public int? 部材番号_MaterialNumber { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public int? 部材FLG_MaterialFlag { get; set; }

    public int? 分類1_Category1 { get; set; }

    public int? 分類2_Category2 { get; set; }

    public int? 分類3_Category3 { get; set; }

    public int? 分類4_Classification4 { get; set; }

    public string 部材名_MaterialName { get; set; }

    public string 部材名1_MaterialName1 { get; set; }

    public string 部材名2_MaterialName2 { get; set; }

    public string 部材名3_MaterialName3 { get; set; }

    public string 部材名4_MaterialName4 { get; set; }

    public string 部材明細_MaterialDetails { get; set; }

    public string 形状寸法_ShapeAndSize { get; set; }

    public byte? 部材GRP_MaterialGroup { get; set; }

    public float? 数量_Quantity { get; set; }

    public int? 単位CD_UnitCode { get; set; }

    public string 単位_Unit { get; set; }

    public int? 支給区分CD_SupplyCategoryCode { get; set; }

    public string 支給区分名_SupplyCategoryName { get; set; }

    public decimal? 塗装費_PaintingCost { get; set; }

    public decimal? 天井開口_CeilingOpening { get; set; }

    public decimal? 標準単価_StandardUnitPrice { get; set; }

    public decimal? 提出単価_SubmittedUnitPrice { get; set; }

    public decimal? 社内単価_InternalUnitPrice { get; set; }

    public decimal? 複合単価_CompositeUnitPrice { get; set; }

    public float? 補給率_SupplyRate { get; set; }

    public float? 付属品率_AccessoriesRate { get; set; }

    public float? 雑材率_MiscellaneousMaterialsRate { get; set; }

    public int? 労務単価A_LaborUnitPriceA { get; set; }

    public decimal? 歩掛A_LaborA { get; set; }

    public float? 撤去率A_RemovalRateA { get; set; }

    public int? 労務単価B_LaborUnitPriceB { get; set; }

    public float? 歩掛B_LaborB { get; set; }

    public float? 撤去率B_RemovalRateB { get; set; }

    public float? その他_Other { get; set; }

    public decimal? 材料費小計_MaterialCostSubtotal { get; set; }

    public decimal? 労務費小計_LaborCostSubtotal { get; set; }

    public int? 素材分類CD_MaterialCategoryCode { get; set; }

    public string 素材分類名_MaterialCategoryName { get; set; }

    public byte? ABC材_ABCMaterials { get; set; }

    public DateTimeOffset 日付追加_DateAdded { get; set; }
    public DateTimeOffset 最終更新日_LastUpdated { get; set; }
}