// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_MsgTable
{
    public string MsgCD { get; set; }

    public byte? MsgPattern { get; set; }

    public short? MsgLine { get; set; }

    public string Msg1 { get; set; }

    public string Msg2 { get; set; }

    public string Msg3 { get; set; }

    public string Msg4 { get; set; }

    public string Msg5 { get; set; }

    public string Command { get; set; }
}