// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_PaperSize
{
    public short? No { get; set; }

    public string PaperSize { get; set; }
}