// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_グループ名マスタ_TM_GroupNameMaster
{
    public int? GPCD { get; set; }

    public int? 表示順 { get; set; }

    public string GP名 { get; set; }

    public bool? 選択FLG { get; set; }

    public int? 仕入先CD1 { get; set; }

    public int? 仕入先CD2 { get; set; }

    public int? 仕入先CD3 { get; set; }
}