// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ComMS.Models;

public partial class TM_仕入先マスタ_TM_VendorMaster
{
    [Key]
    public int? 仕入先CD_SupplierCode { get; set; }

    public int? グループCD_GroupCode { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public string フリガナ_Furigana { get; set; }

    public string 仕入先名_SupplierName { get; set; }

    public string 支社名_BranchName { get; set; }

    public string 郵便番号_PostalCode { get; set; }

    public int? 都道府県CD_PrefectureCode { get; set; }

    public string 都道府県名_PrefectureName { get; set; }

    public int? 市町村CD_MunicipalityCode { get; set; }

    public string 市町村名_MunicipalityName { get; set; }

    public string 住所1_Address1 { get; set; }

    public string 住所2_Address2 { get; set; }

    public string 電話番号1_Telephone1 { get; set; }

    public string 電話番号2_Telephone2 { get; set; }

    public DateTime? 締切日_ClosingDate { get; set; }

    public string ランク_Rank { get; set; }

    public string FAX1_Fax1 { get; set; }

    public string FAX2_Fax2 { get; set; }

    public string eメール_Email { get; set; }

    public string HPアドレス_HomepageAddress { get; set; }

    public string 担当者_PersonInCharge { get; set; }

    public int? 出力帳票形式1_OutputReportFormat1 { get; set; }

    public int? 出力帳票形式2_OutputReportFormat2 { get; set; }

    public bool? 請求初期FLG_InitialBillingFlag { get; set; }

    public bool? 積算初期FLG_InitialEstimationFlag { get; set; }

    public string 備考_Remarks { get; set; }
    public DateTimeOffset 登録日_RegistrationDate { get; set; }
    public DateTimeOffset 更新日_UpdateDate { get; set; }
}