// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_工事名マスタ_TM_Constructionnamemaster
{
    public short? 工事CD_ConstructionCode { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public string 工事名_ConstructionName { get; set; }

    public bool? 削除FLG_DeleteFlag { get; set; }
}