// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_単位マスタ_TM_UnitMaster
{
    public int? 単位CD_UnitCode { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public string 単位名_UnitName { get; set; }

    public bool? 削除FLG_DeleteFlag { get; set; }
}