// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_市町村マスタ_TM_MunicipalityMaster
{
    public short? 都道府県CD_PrefectureCode { get; set; }

    public short? 場所分類1_LocationCategory1 { get; set; }

    public short? 場所分類2_LocationCategory2 { get; set; }

    public short? 場所分類3_LocationCategory3 { get; set; }

    public string 場所名_LocationName { get; set; }

    public bool? 削除フラグ_DeleteFlag { get; set; }
}