// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_分類4マスタ_Category4Master
{
    public short? 分類1_Category1 { get; set; }

    public short? 分類2_Category2 { get; set; }

    public short? 分類3_Category3 { get; set; }

    public short? 分類4_Category4 { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public string 分類名_CategoryName { get; set; }

    public bool? 選択FLG_SelectionFlag { get; set; }

    public bool? 明細FLG_DetailFlag { get; set; }

    public bool? 削除FLG_DeletionFlag { get; set; }
}