// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_家電分類2マスタ_TM_HomeApplianceClassification2Master
{
    public short? 分類1_Category { get; set; }

    public short? 分類2_Category { get; set; }

    public string 家電CD_ApplianceCode { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public string データ名_DataName { get; set; }

    public bool? 削除FLG_DeletionFlag { get; set; }

    public int? 標準単価_StandardPrice { get; set; }
}