// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_工種マスタ_TM_ConstructionTypeMaster
{
    public int? 工種CD_WorkTypeCode { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public string 工種名_WorkTypeName { get; set; }

    public bool? 削除FLG_DeleteFlag { get; set; }

    public float? 雑材消耗率_MiscellaneousMaterialConsumptionRate { get; set; }
}