// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_変換単位マスタ_TMUnitConversionMaster
{
    public double? 分類1_Category1 { get; set; }

    public double? 分類2_Category2 { get; set; }

    public double? 分類3_Category3 { get; set; }

    public double? 分類4_Category4 { get; set; }

    public string 分類名_CategoryName { get; set; }

    public string 部材名_MaterialName { get; set; }

    public short? 単位CD_UnitCode { get; set; }

    public string 単位_Unit { get; set; }

    public short? 変換単位CD_ConversionUnitCode { get; set; }

    public string 変換単位_ConversionUnit { get; set; }

    public float? 変換係数_ConversionCoefficient { get; set; }

    public bool? 削除FLG_DeletionFlag { get; set; }
}