// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_明細戻り_TM_ItemReturn
{
    public byte? 分類_Category { get; set; }

    public short? CD_Code { get; set; }

    public string 名称_Name { get; set; }

    public bool? 削除FLG_DeletionFlag { get; set; }

    public int? 表示順_DisplayOrder { get; set; }
}