// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_明細補助マスタ_TM_AuxiliaryItemMaster
{
    public double? 分類1_Category1 { get; set; }

    public double? 分類2_Category2 { get; set; }

    public double? 分類3_Category3 { get; set; }

    public double? 分類4_Category4 { get; set; }

    public string 部材名_MaterialName { get; set; }

    public string 明細補助F_DetailSupplementF { get; set; }

    public string 明細補助B_DetailSupplementB { get; set; }
}