// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_暦マスタ_TM_CalendarMaster
{
    public byte? 暦CD_CalendarCode { get; set; }

    public string 暦名_CalendarName { get; set; }

    public short? 変更年_ChangeYear { get; set; }
}