// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_素材分類マスタ_TM_MaterialClassificationMaster
{
    public byte? 分類番号_CategoryNumber { get; set; }

    public short? 素材分類CD_MaterialCategoryCode { get; set; }

    public short? 表示順_DisplayOrder { get; set; }

    public string 素材分類名_MaterialCategoryName { get; set; }

    public byte? ABC材_ABCMaterial { get; set; }

    public bool? NetFLG_NetFlag { get; set; }

    public float? 乗率標準設定_RateStandardSetting { get; set; }

    public float? 原価率標準設定_CostRateStandardSetting { get; set; }

    public byte? GP番号1_GPNumber1 { get; set; }

    public byte? GP番号2_GPNumber2 { get; set; }

    public byte? GP番号3_GPNumber3 { get; set; }

    public bool? GP番号4_GPNumber4 { get; set; }

    public string 表示素材分類名_DisplayedMaterialCategoryName { get; set; }

    public float? その他率設定_OtherRateSetting { get; set; }
}