// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_追加品目マスタ_TM_AdditionalMaterialMaster
{
    public short? 分類1_Category1 { get; set; }

    public short? 分類2_Category2 { get; set; }

    public short? 分類3_Category3 { get; set; }

    public short? 分類4_Category4 { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public int? 素材CD_MaterialCode { get; set; }

    public string 分類名_CategoryName { get; set; }

    public string 部材名_MaterialName { get; set; }

    public string 素材名_MaterialName { get; set; }

    public decimal? 標準単価_StandardUnitPrice { get; set; }

    public decimal? 提出単価_SubmissionUnitPrice { get; set; }

    public decimal? 社内単価_InternalUnitPrice { get; set; }

    public decimal? 建物単価_BuildingUnitPrice { get; set; }

    public decimal? 積資単価_AccumulatedResourceUnitPrice { get; set; }

    public decimal? 複合単価_CompositeUnitPrice { get; set; }

    public float? 補給率_SupplyRate { get; set; }

    public float? 付属品率_AccessoryRate { get; set; }

    public float? 雑材率_MiscellaneousMaterialRate { get; set; }

    public int? 労務単価A_LaborUnitPriceA { get; set; }

    public float? 歩掛A_WorkRateA { get; set; }

    public float? 撤去率A_RemovalRateA { get; set; }

    public int? 労務単価B_LaborUnitPriceB { get; set; }

    public float? 歩掛B_WorkRateB { get; set; }

    public float? 撤去率B_RemovalRateB { get; set; }

    public float? その他_Other { get; set; }

    public short? 単位CD_UnitCode { get; set; }

    public string 単位_Unit { get; set; }

    public byte? ABC材_ABCMaterial { get; set; }

    public bool? 明細FLG_DetailFlag { get; set; }

    public short? 素材分類CD_MaterialClassificationCode { get; set; }

    public bool? 選択FLG_SelectionFlag { get; set; }

    public decimal? 天井開口費_CeilingOpeningCost { get; set; }

    public DateTime? 更新日付_UpdatedDate { get; set; }

    public string 更新者_UpdatedBy { get; set; }
}