// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TM_配線器具マスタ_TM_WiringFixtureMaster
{
    public byte? 配線器具種別_WiringDeviceType { get; set; }

    public short? 配線分類CD_WiringClassificationCode { get; set; }

    public string 配線分類名称_WiringClassificationName { get; set; }

    public short? 配線器具CD_WiringDeviceCode { get; set; }

    public string 配線器具名称_WiringDeviceName { get; set; }

    public byte? 分類CD_ClassificationCode { get; set; }

    public byte? プレートCD_PlateCode { get; set; }

    public bool? ハンドルFLG_HandleFlag { get; set; }

    public byte? 個口_Unit { get; set; }

    public float? 歩掛_WorkRate { get; set; }

    public decimal? 提出単価_SubmittedUnitPrice { get; set; }

    public decimal? 社内単価_InternalUnitPrice { get; set; }

    public decimal? 複合単価_CompositeUnitPrice { get; set; }

    public decimal? 販売定価_SellingPrice { get; set; }

    public float? 原価率_CostRate { get; set; }

    public byte? 取付枠FLG_MountingFrameFlag { get; set; }

    public int? BackColor_BackgroundColor { get; set; }
}