// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TR_内訳複合データ_CompositeBreakdownData
{
    public int? 表示順_DisplayOrder { get; set; }

    public int? ＧP番号_GPNumber { get; set; }

    public string 頁番号_PageNumber { get; set; }

    public string 番号_Number { get; set; }

    public int? 工種番号_WorkTypeNumber { get; set; }

    public string 品名及び名称_ItemNameAndDescription { get; set; }

    public string 項目_Item { get; set; }

    public string 形状寸法_ShapeAndDimensions { get; set; }

    public float? 数量_Quantity { get; set; }

    public string 単位_Unit { get; set; }

    public string 支給区分名_SupplyCategoryName { get; set; }

    public float? 補給率_SupplyRate { get; set; }

    public float? 付属品率_AccessoryRate { get; set; }

    public float? 雑材消耗率_MiscMaterialConsumptionRate { get; set; }

    public float? その他_Other { get; set; }

    public decimal? 単価_UnitPrice { get; set; }

    public decimal? 提出単価_QuotedUnitPrice { get; set; }

    public decimal? 社内単価_InternalUnitPrice { get; set; }

    public decimal? 複合単価A_CompositeUnitPriceA { get; set; }

    public decimal? 複合単価B_CompositeUnitPriceB { get; set; }

    public float? 歩掛A_UnitLaborA { get; set; }

    public float? 歩掛B_UnitLaborB { get; set; }

    public decimal? 提出金額_QuotedAmount { get; set; }

    public decimal? 社内金額_InternalAmount { get; set; }

    public short? 素材分類CD_MaterialCategoryCD { get; set; }

    public string 素材分類名_MaterialCategoryName { get; set; }
}