// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TR_工種明細データ_WorkTypeDetailData
{
    public int? GP番号_GPNumber { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public string No_SequenceNumber { get; set; }

    public short? 工種番号_WorkTypeNumber { get; set; }

    public string 工種名1_WorkTypeName1 { get; set; }

    public string 工種名2_WorkTypeName2 { get; set; }

    public float? 数量_Quantity { get; set; }

    public string 単位_Unit { get; set; }

    public decimal? 単価_UnitPrice { get; set; }

    public decimal? 金額_TotalAmount { get; set; }

    public string 備考_Remarks { get; set; }

    public bool? 合計フラグ_TotalFlag { get; set; }

    public string 予備1_Reserve1 { get; set; }
}