// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TR_積算一覧データ_QuotationListData
{
    public int? 見積番号_QuotationNumber { get; set; }

    public string 作成者CD_CreatorCode { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public byte? GP番号_GPNumber { get; set; }

    public string 表示見積番号_DisplayQuotationNumber { get; set; }

    public string 提出先1_SubmitTo1 { get; set; }

    public string 提出先2_SubmitTo2 { get; set; }

    public string 工事名称_ProjectName { get; set; }

    public string 工事場所_ProjectLocation { get; set; }

    public string 期限_Deadline { get; set; }

    public string 条件_Conditions { get; set; }

    public decimal? 見積額_QuotationAmount { get; set; }

    public decimal? 諸経費_MiscellaneousExpenses { get; set; }

    public decimal? 原価_Cost { get; set; }

    public decimal? 粗利_GrossProfit { get; set; }

    public string 作成者_Creator { get; set; }

    public string 仕入先_Supplier { get; set; }

    public byte? 計算種別_CalculationType { get; set; }
}