// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TR_複合単価データ_CompositeUnitPriceData
{
    public int? 表示順_DisplayOrder { get; set; }

    public int? ＧP番号_GPNumber { get; set; }

    public string 頁番号_PageNumber { get; set; }

    public string 番号_Number { get; set; }

    public string 部材名_MaterialName { get; set; }

    public decimal? 単価_UnitPrice { get; set; }

    public float? 補給率_ReplenishmentRate { get; set; }

    public float? 付属品率_AccessoriesRate { get; set; }

    public float? 雑材率_MiscellaneousMaterialRate { get; set; }

    public decimal? 労務単価A_LaborUnitPriceA { get; set; }

    public float? 歩掛A_WorkEfficiencyA { get; set; }

    public float? 撤去率A_RemovalRateA { get; set; }

    public decimal? 労務単価B_LaborUnitPriceB { get; set; }

    public float? 歩掛B_WorkEfficiencyB { get; set; }

    public float? 撤去率B_RemovalRateB { get; set; }

    public float? その他_Other { get; set; }

    public string 単位_Unit { get; set; }

    public decimal? 材料費小計_MaterialCostSubtotal { get; set; }

    public decimal? 労務費小計_LaborCostSubtotal { get; set; }

    public decimal? 複合単価小計_CompositeUnitPriceSubtotal { get; set; }

    public string 補助_Supplementary { get; set; }

    public bool? 空白FLG_BlankFlag { get; set; }

    public bool? 合計フラグ_TotalFlag { get; set; }
}