// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TW_ファンクション_Function
{
    public int? 表示順_DisplayOrder { get; set; }

    public string ファンクション名_FunctionName { get; set; }
}