// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TW_引用部材乗率データ_ReferencedMaterialLoadingRateData
{
    public int? 見積番号_QuotationNumber { get; set; }

    public string 作成者CD_CreatorCode { get; set; }

    public int? 工種番号_ConstructionTypeNumber { get; set; }

    public short? 部材番号_MaterialNumber { get; set; }

    public byte? 案_Plan { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public byte? 分類FLG_CategoryFlag { get; set; }

    public byte? 工種FLG_ConstructionTypeFlag { get; set; }

    public byte? 工種Child_WorkTypeChild { get; set; }

    public short? 部材FLG_MaterialFlag { get; set; }

    public string 品名及び名称_ItemNameAndDescription { get; set; }

    public string 項目_Item { get; set; }

    public string 形状寸法_Dimension { get; set; }

    public float? 数量_Quantity { get; set; }

    public float? 補給率_FillRate { get; set; }

    public float? 提出数量_SubmittedQuantity { get; set; }

    public float? NET率_NETRate { get; set; }

    public float? 社内数量_InHouseQuantity { get; set; }

    public float? 付属品率_AccessoryRate { get; set; }

    public short? 単位CD_UnitCode { get; set; }

    public string 単位_Unit { get; set; }

    public short? 支給区分CD_SupplyCategoryCode { get; set; }

    public string 支給区分名_SupplyCategoryName { get; set; }

    public byte? 単価計算FLG_PriceCalculationFlag { get; set; }

    public decimal? 単価_Price { get; set; }

    public float? 乗率_LoadingRate { get; set; }

    public decimal? 提出単価_SubmittedPrice { get; set; }

    public float? 原価率_CostRate { get; set; }

    public decimal? 社内単価_InHousePrice { get; set; }

    public float? 歩掛_WorkHours { get; set; }

    public float? 雑材消耗率_MiscellaneousMaterialConsumptionRate { get; set; }

    public float? 塗装係数_PaintingCoefficient { get; set; }

    public float? 天井開口係数_CeilingOpeningCoefficient { get; set; }

    public decimal? 提出金額_QuotationAmount { get; set; }

    public decimal? 社内金額_InHouseAmount { get; set; }

    public short? 素材分類CD_MaterialCategoryCode { get; set; }

    public string 素材分類名_MaterialCategoryName { get; set; }

    public byte? ABC材_ABCMaterial { get; set; }

    public int? 新工種番号_NewWorkTypeNumber { get; set; }

    public short? 新部材番号_NewMaterialNumber { get; set; }
}