// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TW_工種並替えワーク_WorkTypeReorderingWork
{
    public int? 見積番号_QuotationNumber { get; set; }

    public string 作成者CD_CreatorCode { get; set; }

    public int? 工種番号_WorkTypeNumber { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public string 表示工種番号_DisplayWorkTypeNumber { get; set; }

    public byte? 工種FLG_WorkTypeFlag { get; set; }

    public byte? 工種Child_WorkTypeChild { get; set; }

    public int? 工種CD_WorkTypeCode { get; set; }

    public string 工種名_WorkTypeName { get; set; }

    public float? 雑材消耗率_MiscellaneousMaterialConsumptionRate { get; set; }

    public bool? 雑材消耗FLG_MiscellaneousMaterialConsumptionFlag { get; set; }

    public byte? 戸数_NumberOfUnits { get; set; }

    public decimal? 提出金額_SubmittedAmount { get; set; }

    public decimal? 社内金額_InternalAmount { get; set; }

    public decimal? 機材費A_EquipmentCostA { get; set; }

    public decimal? 機材費B_EquipmentCostB { get; set; }

    public decimal? 雑材消耗品費A_MiscellaneousMaterialConsumptionCostA { get; set; }

    public decimal? 雑材消耗品費B_MiscellaneousMaterialConsumptionCostB { get; set; }

    public decimal? 労務費A_LaborCostA { get; set; }

    public decimal? 労務費B_LaborCostB { get; set; }

    public decimal? 付帯工事A_AdditionalWorkA { get; set; }

    public decimal? 付帯工事B_AdditionalWorkB { get; set; }

    public decimal? 共通費A_CommonCostA { get; set; }

    public decimal? 共通費B_CommonCostB { get; set; }

    public decimal? 現場雑費A_OnSiteMiscellaneousExpensesA { get; set; }

    public decimal? 現場雑費B_OnSiteMiscellaneousExpensesB { get; set; }

    public decimal? 諸経費A_VariousExpensesA { get; set; }

    public decimal? 諸経費B_VariousExpensesB { get; set; }

    public int? 正表示順_CorrectDisplayOrder { get; set; }
}