// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TW_合成単価データ_CombinedUnitPriceData
{
    public int? 見積番号_QuotationNumber { get; set; }

    public short? 工種番号_WorkTypeNumber { get; set; }

    public short? 部材番号_MaterialNumber { get; set; }

    public string 作成者CD_CreatorCode { get; set; }

    public int? 補助番号_AssistanceNumber { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public short? 分類1_Category1 { get; set; }

    public short? 分類2_Category2 { get; set; }

    public short? 分類3_Category3 { get; set; }

    public short? 分類4_Category4 { get; set; }

    public string 部材名_MaterialName { get; set; }

    public string 部材名1_MaterialName1 { get; set; }

    public string 部材名2_MaterialName2 { get; set; }

    public string 部材名3_MaterialName3 { get; set; }

    public string 部材名4_MaterialName4 { get; set; }

    public float? 数量_Quantity { get; set; }

    public decimal? 単価_UnitPrice { get; set; }

    public float? 歩掛_WorkRatio { get; set; }

    public string 単位_Unit { get; set; }

    public byte? 補助FLG_AssistanceFlag { get; set; }

    public string 補助_Assistance { get; set; }
}