// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TW_検索素材マスタ_SearchMaterialMaster
{
    public short? 分類1_Category1 { get; set; }

    public short? 分類2_Category2 { get; set; }

    public short? 分類3_Category3 { get; set; }

    public short? 分類4_Category4 { get; set; }

    public byte? マスタFLG_MasterFlag { get; set; }

    public string 素材CD_MaterialCode { get; set; }

    public string 分類名_CategoryName { get; set; }

    public string 部材名_ComponentName { get; set; }

    public decimal? 標準単価_StandardUnitPrice { get; set; }

    public decimal? 提出単価_QuotedUnitPrice { get; set; }

    public decimal? 社内単価_InHouseUnitPrice { get; set; }

    public decimal? 建物単価_BuildingUnitPrice { get; set; }

    public decimal? 積資単価_AccumulatedMaterialUnitPrice { get; set; }

    public decimal? 複合単価_CompositeUnitPrice { get; set; }

    public decimal? 電設資材_ElectricalMaterials { get; set; }

    public float? 電設乗率_ElectricalLoadingRate { get; set; }

    public float? 電設原価率_ElectricalCostRate { get; set; }

    public float? 補給率_SupplyRate { get; set; }

    public float? 付属品率_AccessoryRate { get; set; }

    public float? 雑材率_MiscellaneousMaterialRate { get; set; }

    public int? 労務単価A_LaborUnitPriceA { get; set; }

    public float? 歩掛A_WorkRateA { get; set; }

    public float? 撤去率A_RemovalRateA { get; set; }

    public int? 労務単価B_LaborUnitPriceB { get; set; }

    public float? 歩掛B_WorkRateB { get; set; }

    public float? 撤去率B_RemovalRateB { get; set; }

    public float? その他_Other { get; set; }

    public short? 単位CD_UnitCode { get; set; }

    public string 単位_Unit { get; set; }

    public short? 素材分類CD_MaterialCategoryCode { get; set; }

    public string 素材分類名_MaterialCategoryName { get; set; }

    public byte? ABC材_ABCMaterial { get; set; }

    public DateTime? 更新日付_UpdateDate { get; set; }

    public string 更新者_Updater { get; set; }

    public decimal? 天井開口費_CeilingOpeningCost { get; set; }
}