// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TW_明細分析データ_DetailAnalysisData
{
    public int? 見積番号_QuotationNumber { get; set; }

    public string 作成者CD_CreatorCode { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public byte? GP番号_GPNumber { get; set; }

    public decimal? B材_A_MaterialB_A { get; set; }

    public decimal? 電線類_A_Wires_A { get; set; }

    public decimal? A材_A_MaterialA_A { get; set; }

    public decimal? 防災_A_DisasterPrevention_A { get; set; }

    public decimal? 雑材_A_MiscMaterials_A { get; set; }

    public decimal? 労務費_A_LaborCosts_A { get; set; }

    public decimal? 外注費_A_SubcontractingCosts_A { get; set; }

    public decimal? 付帯工事_A_AccessoryWork_A { get; set; }

    public decimal? 共通費_A_CommonCosts_A { get; set; }

    public decimal? 現場雑費_A_SiteMiscellaneousCosts_A { get; set; }

    public decimal? 諸経費_A_VariousCosts_A { get; set; }

    public decimal? 共通仮設費_A_CommonTemporaryCosts_A { get; set; }

    public decimal? 現場管理費_A_SiteManagementCosts_A { get; set; }

    public decimal? 一般管理費_A_GeneralManagementCosts_A { get; set; }

    public decimal? 材料小計_A_MaterialSubtotal_A { get; set; }

    public decimal? 労務小計_A_LaborSubtotal_A { get; set; }

    public decimal? 経費小計_A_CostSubtotal_A { get; set; }

    public decimal? 総計_A_Total_A { get; set; }

    public decimal? B材_B_MaterialB_B { get; set; }

    public decimal? 電線類_B_Wires_B { get; set; }

    public decimal? A材_B_MaterialA_B { get; set; }

    public decimal? 雑材_B_MiscMaterials_B { get; set; }

    public decimal? 防災_B_DisasterPrevention_B { get; set; }

    public decimal? 労務費_B_LaborCosts_B { get; set; }

    public decimal? 外注費_B_SubcontractingCosts_B { get; set; }

    public decimal? 付帯工事_B_AccessoryWork_B { get; set; }

    public decimal? 共通費_B_CommonCosts_B { get; set; }

    public decimal? 現場雑費_B_SiteMiscellaneousCosts_B { get; set; }

    public decimal? 諸経費_B_VariousCosts_B { get; set; }

    public decimal? 共通仮設費_B_CommonTemporaryCosts_B { get; set; }

    public decimal? 現場管理費_B_SiteManagementCosts_B { get; set; }

    public decimal? 一般管理費_B_GeneralManagementCosts_B { get; set; }

    public decimal? 材料小計_B_MaterialSubtotal_B { get; set; }

    public decimal? 労務小計_B_LaborSubtotal_B { get; set; }

    public decimal? 経費小計_B_CostSubtotal_B { get; set; }

    public decimal? 総計_B_Total_B { get; set; }
}