// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TW_総合複合単価ワーク_OverallCompositeUnitPriceWork
{
    public int? 見積番号_QuotationNumber { get; set; }

    public short? 工種番号_ConstructionTypeNumber { get; set; }

    public short? 部材番号_MaterialNumber { get; set; }

    public string 作成者CD_CreatorCode { get; set; }

    public int? 補助番号_AssistanceNumber { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public int? 補助表示順_AssistanceDisplayOrder { get; set; }

    public string 部材名_MaterialName { get; set; }

    public decimal? 建物単価_BuildingUnitPrice { get; set; }

    public decimal? 積資単価_AccumulatedMaterialUnitPrice { get; set; }

    public float? 補給率_ReplacementRate { get; set; }

    public float? 付属品率_AdditionalRate { get; set; }

    public float? 雑材率_MiscellaneousMaterialRate { get; set; }

    public decimal? 労務単価A_LaborUnitPriceA { get; set; }

    public float? 歩掛A_WorkHoursRateA { get; set; }

    public float? 撤去率A_RemovalRateA { get; set; }

    public decimal? 労務単価B_LaborUnitPriceB { get; set; }

    public float? 歩掛B_WorkHoursRateB { get; set; }

    public float? 撤去率B_RemovalRateB { get; set; }

    public float? その他_Other { get; set; }

    public string 単位_Unit { get; set; }

    public decimal? 材料費小計_MaterialCostSubtotal { get; set; }

    public decimal? 労務費小計_LaborCostSubtotal { get; set; }

    public decimal? 複合単価小計_CompositeUnitPriceSubtotal { get; set; }

    public byte? 補助FLG_AssistanceFlag { get; set; }

    public string 補助_Assistance { get; set; }

    public byte? 入力FLG_InputFlag { get; set; }
}