// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TW_追加並替えワーク_AdditionalReorderingWork
{
    public short? 分類1_Category1 { get; set; }

    public short? 分類2_Category2 { get; set; }

    public short? 分類3_Category3 { get; set; }

    public short? 分類4_Category4 { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public int? 素材CD_MaterialCode { get; set; }

    public string 分類名_CategoryName { get; set; }

    public string 部材名_MaterialName { get; set; }

    public string 素材名_MaterialName { get; set; }

    public decimal? 標準単価_StandardUnitPrice { get; set; }

    public decimal? 提出単価_SubmittedUnitPrice { get; set; }

    public decimal? 社内単価_InternalUnitPrice { get; set; }

    public decimal? 建物単価_BuildingUnitPrice { get; set; }

    public decimal? 積資単価_AccumulatedMaterialUnitPrice { get; set; }

    public decimal? 複合単価_CompositeUnitPrice { get; set; }

    public float? 補給率_ReplacementRate { get; set; }

    public float? 付属品率_AdditionalRate { get; set; }

    public float? 雑材率_MiscellaneousMaterialRate { get; set; }

    public int? 労務単価A_LaborUnitPriceA { get; set; }

    public float? 歩掛A_WorkHoursRateA { get; set; }

    public float? 撤去率A_RemovalRateA { get; set; }

    public int? 労務単価B_LaborUnitPriceB { get; set; }

    public float? 歩掛B_WorkHoursRateB { get; set; }

    public float? 撤去率B_RemovalRateB { get; set; }

    public float? その他_Other { get; set; }

    public short? 単位CD_UnitCode { get; set; }

    public string 単位_Unit { get; set; }

    public byte? ABC材_ABCMaterial { get; set; }

    public bool? 明細FLG_DetailFlag { get; set; }

    public short? 素材分類CD_MaterialCategoryCode { get; set; }

    public int? 正表示順_CorrectDisplayOrder { get; set; }

    public bool? 選択FLG_SelectionFlag { get; set; }
}