// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TW_製作所データ_ProducersData
{
    public short? No_Number { get; set; }

    public string 製作所名_ProducersName { get; set; }
}