// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TW_計算式_CalculationFormula
{
    public byte? No_Number { get; set; }

    public string 計算項目_CalculationItem { get; set; }

    public bool? 表示FLG_DisplayFlag { get; set; }
}