// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TW_複合単価データ_CompositeUnitPriceData
{
    public int? 見積番号_QuotationNumber { get; set; }

    public short? 工種番号_ConstructionTypeCode { get; set; }

    public short? 部材番号_MaterialCode { get; set; }

    public string 作成者CD_CreatorCode { get; set; }

    public int? 補助番号_SupportNumber { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public int? 補助表示順_SupportDisplayOrder { get; set; }

    public string 部材名_MaterialName { get; set; }

    public decimal? 建物単価_BuildingPrice { get; set; }

    public decimal? 積資単価_AccumulatedMaterialPrice { get; set; }

    public float? 補給率_SupplyRate { get; set; }

    public float? 付属品率_AccessoryRate { get; set; }

    public float? 雑材率_MiscellaneousMaterialRate { get; set; }

    public decimal? 労務単価A_LaborPriceA { get; set; }

    public float? 歩掛A_WorkRateA { get; set; }

    public float? 撤去率A_RemovalRateA { get; set; }

    public decimal? 労務単価B_LaborPriceB { get; set; }

    public float? 歩掛B_WorkRateB { get; set; }

    public float? 撤去率B_RemovalRateB { get; set; }

    public float? その他_Others { get; set; }

    public string 単位_Unit { get; set; }

    public decimal? 材料費小計_MaterialCostSubtotal { get; set; }

    public decimal? 労務費小計_LaborCostSubtotal { get; set; }

    public decimal? 複合単価小計_CompositePriceSubtotal { get; set; }

    public byte? 補助FLG_SupportFlag { get; set; }

    public string 補助_Support { get; set; }

    public byte? 入力FLG_InputFlag { get; set; }
}