// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComMS.Models;

public partial class TW_集計工種選択_AggregationWorkTypeSelection
{
    public short? 工種番号_WorkTypeNumber { get; set; }

    public int? 表示順_DisplayOrder { get; set; }

    public string 工種名_WorkTypeName { get; set; }
}